//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_TekBot_Prod_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int CaseId { get; set; }
        public string Engineer_name { get; set; }
        public string Team { get; set; }
        public string Case_number { get; set; }
        public string Case_type { get; set; }
        public string Case_Status { get; set; }
        public string Case_severity { get; set; }
        public string Full_Date { get; set; }
        public Nullable<int> Day_Number { get; set; }
        public Nullable<int> Month_Number { get; set; }
        public Nullable<int> Week_Year { get; set; }
        public Nullable<int> Year_Number { get; set; }
        public string Day_Name { get; set; }
        public string Month_Name { get; set; }
        public string Comments { get; set; }
        public string AssignedBy { get; set; }
        public string Full_Date_Close { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
    }
}
