//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_TekBot_Prod_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string mail { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<System.DateTime> Last_Review { get; set; }
        public string Users_Status { get; set; }
        public string Users_positions { get; set; }
        public Nullable<int> Users_vacations { get; set; }
        public int User_Number { get; set; }
        public Nullable<int> QAUser_type { get; set; }
        public Nullable<int> Users_Role { get; set; }
        public string User_Password { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
